development:
    app_key: 5akj4m5oce33eca
    app_secret: l37kvlvg4efafka
    access_token: 4gompz2huizz4i4
    access_token_secret: mv3fxhdny2fmtga
    user_id: 6620118
    access_type: dropbox
production:
    app_key: 5akj4m5oce33eca
    app_secret: l37kvlvg4efafka
    access_token: 4gompz2huizz4i4
    access_token_secret: mv3fxhdny2fmtga
    user_id: 6620118
    access_type: dropbox